[package]
name = "MStarPlayer-mqtt-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.34"
env_logger = "0.11.11"
rumqttc = "0.25.1"
slint = "1.17.1"

[dev-dependencies]
mockall = "0.15.0"

[lib]
crate-type=["lib", "cdylib"]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
wildcard_imports = { level = "allow" }
missing-panics-doc = { level = "allow" }
